from typing import List, Dict
from .parser import APIEntry
from .badges import BadgeGenerator


class ReadmeGenerator:
    """Generate README with badges for API entries."""
    
    def __init__(self):
        self.badge_generator = BadgeGenerator()
    
    def generate_readme_badges(self, entries: List[APIEntry], output_path: str):
        """Generate README with badges for API entries."""
        # Group entries by category
        categories = self._group_by_category(entries)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("# Public APIs with Badges\n\n")
            f.write("This file contains the same API list as README.md but with additional badges for HTTPS, Auth, and CORS status.\n\n")
            
            # Generate table of contents
            f.write("## Categories\n\n")
            for category in sorted(categories.keys()):
                anchor = category.lower().replace(' ', '-').replace('&', 'and')
                f.write(f"* [{category}](#{anchor})\n")
            f.write("\n")
            
            # Generate tables for each category
            for category, category_entries in sorted(categories.items()):
                f.write(f"## {category}\n\n")
                f.write("API | Description | Auth | HTTPS | CORS | Badges\n")
                f.write("|:---|:---|:---|:---|:---|:---|\n")
                
                for entry in category_entries:
                    badges = self.badge_generator.generate_badges(entry)
                    badge_images = self._format_badge_images(badges)
                    
                    # Escape pipe characters in description
                    description = entry.description.replace('|', '\\|')
                    
                    f.write(f"| [{entry.name}]({entry.link}) | {description} | {entry.auth} | {entry.https} | {entry.cors} | {badge_images} |\n")
                
                f.write("\n")
            
            f.write("\n---\n")
            f.write("*Generated by api-badger*\n")
    
    def _group_by_category(self, entries: List[APIEntry]) -> Dict[str, List[APIEntry]]:
        """Group API entries by category."""
        categories = {}
        for entry in entries:
            category = entry.category or "Uncategorized"
            if category not in categories:
                categories[category] = []
            categories[category].append(entry)
        return categories
    
    def _format_badge_images(self, badges: Dict[str, str]) -> str:
        """Format badge images as markdown."""
        badge_links = []
        for badge_type, badge_url in badges.items():
            badge_links.append(f"![{badge_type}]({badge_url})")
        return " ".join(badge_links)