name: "Tests of push & pull"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FILENAME: README.md

jobs:
  tests:
    name: 'Validate README.md format'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Validate table format
        run: python scripts/validate/format.py ${FILENAME}

